const Translations = {
  eng: {
    log_in: "Log In",
    sign_in: "Sign In",
    skip_signin: "Skip Sign In",
    skip_login: "Skip Login", 
    login_to_your_account: "Login to your account",
    sign_up: "Sign Up",
    sign_up_to_register: "Sign Up to Register",
    skip_and_continue_as_guest: "Skip & Continue as a Guest",
    or: "OR",
    pick_up_date: "Pick Up Date",
    this_booking_is_cancelled:"This booking is cancelled",
    service_time_cancel:"You can cancel 1hr before the service time",
    pick_up_time: "Pick Up Time",
    enter_email_id: "Enter email Id",
    enter_password: "Enter Password",
    skip_and_continue_as_guest: "Skip & Continue as a Guest",
    sign_up_to_register: "Sign Up to Register",
    otp_verification: "OTP Verification",
    enter_otp: "Enter OTP",
    otp_sent_message: "A 4-digit code has been sent to your email",
    otp_resent_message: "OTP has been resent to your email!",
    resend_otp: "Resend OTP",
    submit: "Submit",
    ad: "Ad",
    no_address_found: "No Address Found",
    rate: "Rate",
    no_booking_available: "No Booking Available",
    no_notifications_available: "No Notifications Available",
    flight_number: "Flight Number",
    departure_date: "Departure Date",
    airport: "Airport",
    search: "Search",
    select_date: "Select Date",
    enter_flight_number: "Enter Flight Number",
    services: "Services",
    book_now: "Book Now",
    no_services_available: "No services available",
    active_bookings: "Active Bookings",
    activities: "Activities",
    cancel: "Cancel",
    view_details: "View Details",
    cancel_policy: "You can cancel 1hr before the service time",
    booking_details: "Booking Details",
    baggage_collection: "Baggage Collection",
    baggage_count: "Baggage Count",
    date: "Date",
    time: "Time",
    total_paid: "Total Paid",
    status: "Status",
    pick_up: "Pick up",
    drop_off: "Drop Off",
    contact_info: "Contact Info",
    booking_no: "Booking No",
    cancellation: "Cancellation",
    specify_reason_for_cancellation: "Specify Reason for Cancellation",
    cancellation_note:
      "Note: Once it's submitted, our support team will connect with you to refund the amount with the deducted fine amount.",
    type_here: "Type here...",
    confirm_logout: "Are you sure you want to Logout?",
    logout: "Logout",
    not_now: "Not Now",
    yes_logout: "Yes, Logout",
    delete_account_reason: "Give Reason to Delete your Account.",
    delete_account: "Delete Account",
    reason_service_not_good: "Service is Not Good",
    reason_no_proper_customer_care: "No Proper Customer Care",
    reason_driver_rude: "Driver is Rude",
    reason_poor_experience: "Poor user experience",
    reason_other: "Other reason (Please specify)",
    profile: "Profile",
    edit_profile: "Edit Profile",
    profile_details: "Profile Details",
    add_address: "Add Address",
    address:"Address",
    language: "Language",
    contact_us: "Contact Us",
    chat_with_support: "Chat With Support Team",
    faq: "FAQ",
    feedback: "Feedback",
    terms_and_conditions: "Terms And Conditions",
    privacy_policy: "Privacy Policy",
    from: "From",
    to: "To",
    cancellation_policy: "Cancellation Policy",
    refund_policy: "Refund Policy",
    delete_account: "Delete Account",
    name: "Name",
    enter_name: "Enter Name",
    email_id: "Email Id",
    enter_email_id: "Enter Email Id",
    phone_number: "Phone Number",
    enter_phone_number: "Enter Phone Number",
    save: "Save",
    address: "Address",
    address: "Address",
    book_services: "Book Services",
    for_hassle_free_trip: "for Hassle-free Trip",
    find_flight_to_book_services: "Find your flight in just one click to book services",
    add: "Add",
    city: "City",
    review: "Review",
    enter_address: "Enter Address",
    enter_city: "Enter City",
    state: "State",
    enter_state: "Enter State",
    postal_code: "Postal Code",
    enter_postal_code: "Enter Postal Code",
    location_name: "Location Name",
    english: "English",
    arabic: "Arabic",
    contact_us: "Contact Us",
    send_mail: "Send Mail",
    chat_in_whatsapp: "Chat in WhatsApp",
    call: "Call",
    write_feedback: "Write Feedback on your Latest Service",
    loading_terms_conditions: "Loading terms and conditions...",
    loading_privacy_policy: "Loading privacy policy...",
    loading_refund_policy: "Loading refund policy...",
    loading_cancellation_policy: "Loading cancellation policy...",
    search_result: "Search Result",
    baggage_details: "Baggage Details",
    number_of_persons: "Number of Persons",
    baggage: "Baggage",
    checked_in_bags: "Checked in Bags",
    upload_image: "Upload Image",
    max_file_size: "Max 5MB - JPG, PNG allowed",
    continue: "Continue",
    select_slots: "Select Slots",
    selected_slots: "Selected Slots",
    pick_up_date: "Pick Up Date",
    select_time: "Select Time",
    go_back: "Go Back",
    modify_slot: "Modify Slot",
    select_option: "Select Option",
    pick_up_location: "Pick Up Location",
    pick_up: "Pick Up",
    drop_off: "Drop Off",
    swipe_right_to_book: "Swipe Right to Book",
    notification: "Notification",
    logging_out_message:
    "Logging out will end your session, and you will need to log in again to access your account.",
    select_location: "Select Location",
    total: "Total",
    home: "Home",
    search: "Search",
    entercity:"Enter City",
    enterairportname:"Enter Airport Name ",
    cancelslot:"Cancel Slot",
    app_version: "Version",

    // Placeholders

    email_placeholder: "Enter email ID",
    password_placeholder: "Enter Password",
    name_placeholder: "Enter Name",
    phone_placeholder: "Enter Phone Number",
    otp_placeholder: "Enter OTP",
    address_placeholder: "Enter Address",
    city_placeholder: "Enter City",
    state_placeholder: "Enter State",
    postal_placeholder: "Enter Postal Code",
    location_placeholder: "Enter Location Name",
    reason_placeholder: "Enter Reason",
    comment_placeholder: "Write your feedback here",
    pickup_placeholder: "Select Pick-up Location",
    time_placeholder: "Select Time",
    enter_flight_number: "Enter Flight Number",
    select_date: "Select Date",
    number_of_persons: "Number of Persons",
    checked_in_bags: "Checked in Bags",
    pick_up_timings: "Pick Up Timings",
    pick_up_location: "Pick Up Location",
    write_your_comment: "Write your comment...",


  },
  arb: {
    home: "الرئيسية",
    log_in: "تسجيل الدخول",
    sign_in: "تسجيل الدخول",
    sign_up: "التسجيل",
    skip_login: "تخطي تسجيل الدخول",
    skip_signin:"تخطي إنشاء الحساب",
    login_to_your_account: "تسجيل الدخول إلى حسابك",
    sign_up_to_register: "اشترك للتسجيل",
    skip_and_continue_as_guest: "تخطي والمتابعة كضيف",
    or: "أو",
    enter_email_id: "أدخل معرف البريد الإلكتروني",
    enter_password: "أدخل كلمة المرور",
    skip_and_continue_as_guest: "تخطي والمتابعة كضيف",
    sign_up_to_register: "اشترك للتسجيل",
    otp_verification: "التحقق من OTP",
  enter_otp: "أدخل OTP",
  otp_sent_message: "تم إرسال رمز مكون من 4 أرقام إلى بريدك الإلكتروني",
  otp_resent_message: "تمت إعادة إرسال OTP إلى بريدك الإلكتروني!",
  resend_otp: "إعادة إرسال OTP",
  submit: "إرسال",
  ad: "إعلان",
    search: "بحث",
      this_booking_is_cancelled: "تم إلغاء هذا الحجز",
  service_time_cancel: "يمكنك الإلغاء قبل ساعة واحدة من وقت الخدمة",
    select_date: "حدد التاريخ",
    flight_number: "رقم الرحلة",
    departure_date: "تاريخ المغادرة",
    book_services: "احجز الخدمات",
    for_hassle_free_trip: "لرحلة خالية من المتاعب",
    find_flight_to_book_services: "اعثر على رحلتك بنقرة واحدة فقط لحجز الخدمات",
    enter_flight_number: "أدخل رقم الرحلة",
    services: "الخدمات",
    from: "من",
    to: "إلى",
    pick_up_date: "تاريخ الاستلام",
    pick_up_time: "وقت الاستلام",
    airport: "المطار",
    book_now: "احجز الآن",
    no_services_available: "لا توجد خدمات متاحة",
    active_bookings: "الحجوزات النشطة",
    activities: "الأنشطة",
    cancel: "إلغاء",
    view_details: "عرض التفاصيل",
    cancel_policy: "يمكنك الإلغاء قبل ساعة واحدة من وقت الخدمة",
    booking_details: "تفاصيل الحجز",
    baggage_collection: "استلام الأمتعة",
    baggage_count: "عدد الأمتعة",
    date: "التاريخ",
    time: "الوقت",
    total_paid: "إجمالي المدفوع",
    status: "الحالة",
    go_back: "العودة",
    modify_slot: "تعديل الفتحة",
    pick_up: "الاستلام",
    drop_off: "التوصيل",
    contact_info: "معلومات الاتصال",
    booking_no: "رقم الحجز",
    cancellation: "إلغاء",
    checked_in_bags: "الحقائب المسجلة",
    specify_reason_for_cancellation: "حدد سبب الإلغاء",
    cancellation_note:
      "ملاحظة: بمجرد الإرسال، سيتواصل فريق الدعم معنا لاسترداد المبلغ مع خصم الغرامة.",
    type_here: "اكتب هنا...",
    confirm_logout: "هل أنت متأكد أنك تريد تسجيل الخروج؟",
    logout: "تسجيل الخروج",
    not_now: "ليس الآن",
    yes_logout: "نعم، تسجيل الخروج",
    delete_account_reason: "أذكر سبب حذف حسابك.",
    delete_account: "حذف الحساب",
    reason_service_not_good: "الخدمة ليست جيدة",
    reason_no_proper_customer_care: "لا يوجد دعم عملاء مناسب",
    reason_driver_rude: "السائق غير مهذب",
    reason_poor_experience: "تجربة مستخدم سيئة",
    reason_other: "سبب آخر (يرجى التحديد)",
    profile: "الملف الشخصي",
    edit_profile: "تعديل الملف الشخصي",
    profile_details: "تفاصيل الملف الشخصي",
    add_address: "إضافة عنوان",
    language: "اللغة",
    contact_us: "اتصل بنا",
    chat_with_support: "الدردشة مع فريق الدعم",
    faq: "الأسئلة الشائعة",
    feedback: "ملاحظات",
    terms_and_conditions: "الشروط والأحكام",
    privacy_policy: "سياسة الخصوصية",
    cancellation_policy: "سياسة الإلغاء",
    refund_policy: "سياسة الاسترداد",
    delete_account: "حذف الحساب",
    name: "الاسم",
    enter_name: "أدخل الاسم",
    email_id: "معرف البريد الإلكتروني",
    enter_email_id: "أدخل معرف البريد الإلكتروني",
    phone_number: "رقم الهاتف",
    enter_phone_number: "أدخل رقم الهاتف",
    save: "حفظ",
    address: "العنوان",
    add: "إضافة",
    city: "المدينة",
    enter_address: "أدخل العنوان",
    enter_city: "أدخل المدينة",
    state: "الولاية",
    enter_state: "أدخل الولاية",
    postal_code: "الرمز البريدي",
    enter_postal_code: "أدخل الرمز البريدي",
    location_name: "اسم الموقع",
    english: "الإنجليزية",
    arabic: "العربية",
    contact_us: "اتصل بنا",
    send_mail: "إرسال بريد",
    chat_in_whatsapp: "الدردشة في واتساب",
    call: "اتصال",
    review: "مراجعة",
    write_feedback: "اكتب ملاحظاتك على خدمتك الأخيرة",
    loading_terms_conditions: "جارٍ تحميل الشروط والأحكام...",
    loading_privacy_policy: "جارٍ تحميل سياسة الخصوصية...",
    loading_refund_policy: "جارٍ تحميل سياسة الاسترداد...",
    loading_cancellation_policy: "جارٍ تحميل سياسة الإلغاء...",
    search_result: "نتيجة البحث",
    baggage_details: "تفاصيل الأمتعة",
    number_of_persons: "عدد الأشخاص",
    baggage: "الأمتعة",
    upload_image: "تحميل الصورة",
    max_file_size: "الحد الأقصى 5 ميغابايت - يسمح JPG, PNG",
    continue: "متابعة",
    select_slots: "اختر الفترات",
    selected_slots: "الفترات المحددة",
    pick_up_date: "تاريخ الاستلام",
    select_time: "حدد الوقت",
    select_option: "حدد الخيار",
    pick_up_location: "موقع الاستلام",
    no_address_found: "لا توجد عناوين",
    rate: "تقييم",
    no_booking_available: "لا توجد حجوزات متاحة",
    no_notifications_available: "لا توجد إشعارات متاحة",
    pick_up: "استلام",
    drop_off: "التوصيل",
    swipe_right_to_book: "اسحب لليمين للحجز",
    notification: "إشعار",
    logging_out_message:
    "سيؤدي تسجيل الخروج إلى إنهاء جلستك، وستحتاج إلى تسجيل الدخول مرة أخرى للوصول إلى حسابك.",
    select_location: "اختر الموقع",
    total: "الإجمالي",
    search: "بحث",
    enterairportname:"أدخل المدينة",
    entercity:" أدخل اسم المطار",
    cancelslot:"إلغاء الموعد ",
    app_version: "الإصدار",


    // placeholder

    email_placeholder: "أدخل البريد الإلكتروني",
    password_placeholder: "أدخل كلمة المرور",
    name_placeholder: "أدخل الاسم",
    phone_placeholder: "أدخل رقم الهاتف",
    otp_placeholder: "أدخل رمز التحقق",
    address_placeholder: "أدخل العنوان",
    city_placeholder: "أدخل المدينة",
    state_placeholder: "أدخل الولاية",
    postal_placeholder: "أدخل الرمز البريدي",
    location_placeholder: "أدخل اسم الموقع",
    reason_placeholder: "أدخل السبب",
    comment_placeholder: "اكتب ملاحظاتك هنا",
    pickup_placeholder: "حدد موقع الاستلام",
    time_placeholder: "حدد الوقت",
    enter_flight_number: "أدخل رقم الرحلة",
    select_date: "حدد التاريخ",
    number_of_persons: "عدد الأشخاص",
    checked_in_bags: "الحقائب المسجلة",
    pick_up_timings: "حدد وقت الاستلام",
    pick_up_location: "حدد موقع الاستلام",
    write_your_comment: "اكتب تعليقك...",

  },
}

export default Translations;
